### ISSUE TITLE
How to use Sharpen feature of ImageJ

### ISSUE THREAD

**Issue by NiteshSaxena** [imagej/imagej-node#1]
I am trying to use Sharpen feature of ImageJ Fiji on an Image.
The code I am trying is as follows:

```
config = {}
config.imagej_dir = process.env.IMAGEJ_DIR
config.headless = true
var imagej = require('imagej')(config)
imagej.on('ready', function(ij) {
  dataset = ij.io().open('C:/Users/User1/Desktop/Sample1.tif')
  filtered = ij.op().run('process.sharpen', dataset)  ///This line fails.
  ij.scifio().datasetIO().save(filtered, 'C:/Users/User1/Desktop/1.png')
  ij.context().dispose()
})
```

I have Environment Path set and everything set-up. ImageJ is initializing and image loading but the process fails. Looks like I am not using the API properly. 
Could you please help?
Could you also explain how to use the API's with this library as I want to use some other functions as well?
Help will be greatly appreciated.

**Comment by imagejan** [comment]
> `ij.op().run('process.sharpen', dataset)`

There is no `process.sharpen` op in `imagej-ops` to my knowledge.

As this is a usage question and by no means an issue in `imagej-node`, I suggest you post your question on https://forum.image.sc
