### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by marcmortensen** [imagej/imagej-node#3]
Hey I followed the instructions on how to install and i could not manage to install this package, i was curious and updating the dependencies seems like it is enough to make it run:

npm config set python /usr/bin/python2.7

npm i imagej

`make: *** [nodejavabridge_bindings.target.mk:145: Release/obj.target/nodejavabridge_bindings.node] Error 1
make: Leaving directory '/home/marcm/Documents/Projects/imageJ/cellCounter/node_modules/imagej/node_modules/java/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-40-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/marcm/Documents/Projects/imageJ/cellCounter/node_modules/imagej/node_modules/java
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! java@0.9.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the java@0.9.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/marcm/.npm/_logs/2020-07-14T16_08_08_319Z-debug.log
`
I've tried your code updating the libraries to:

- java -> 0.12.1
- node-java-maven-> 0.1.2,
- when -> 3.7.8

And using your code I've been able to run successfully run ImageJ.

PD: Sorry for creating the last issue, first time using Github, if you need anything just say, and thanks!.

**Comment by marcmortensen** [comment]
I have added https://github.com/imagej/imagej-node/pull/4

**Comment by ctrueden** [comment]
@marcmortensen Thanks for the report, and for the fix! :beers:
